# SPDX-License-Identifier: GPL-2.0-or-later

CMD_VIA_GET_PROTOCOL_VERSION = 0x01
CMD_VIA_GET_KEYBOARD_VALUE = 0x02
CMD_VIA_SET_KEYBOARD_VALUE = 0x03
CMD_VIA_GET_KEYCODE = 0x04
CMD_VIA_SET_KEYCODE = 0x05
CMD_VIA_LIGHTING_SET_VALUE = 0x07
CMD_VIA_LIGHTING_GET_VALUE = 0x08
CMD_VIA_LIGHTING_SAVE = 0x09
CMD_VIA_MACRO_GET_COUNT = 0x0C
CMD_VIA_MACRO_GET_BUFFER_SIZE = 0x0D
CMD_VIA_MACRO_GET_BUFFER = 0x0E
CMD_VIA_MACRO_SET_BUFFER = 0x0F
CMD_VIA_GET_LAYER_COUNT = 0x11
CMD_VIA_KEYMAP_GET_BUFFER = 0x12
CMD_VIA_VIAL_PREFIX = 0xFE
VIA_LAYOUT_OPTIONS = 0x02
VIA_SWITCH_MATRIX_STATE = 0x03
QMK_BACKLIGHT_BRIGHTNESS = 0x09
QMK_BACKLIGHT_EFFECT = 0x0A
QMK_RGBLIGHT_BRIGHTNESS = 0x80
QMK_RGBLIGHT_EFFECT = 0x81
QMK_RGBLIGHT_EFFECT_SPEED = 0x82
QMK_RGBLIGHT_COLOR = 0x83
VIALRGB_GET_INFO = 0x40
VIALRGB_GET_MODE = 0x41
VIALRGB_GET_SUPPORTED = 0x42
VIALRGB_SET_MODE = 0x41
CMD_VIAL_GET_KEYBOARD_ID = 0x00
CMD_VIAL_GET_SIZE = 0x01
CMD_VIAL_GET_DEFINITION = 0x02
CMD_VIAL_GET_ENCODER = 0x03
CMD_VIAL_SET_ENCODER = 0x04
CMD_VIAL_GET_UNLOCK_STATUS = 0x05
CMD_VIAL_UNLOCK_START = 0x06
CMD_VIAL_UNLOCK_POLL = 0x07
CMD_VIAL_LOCK = 0x08
CMD_VIAL_QMK_SETTINGS_QUERY = 0x09
CMD_VIAL_QMK_SETTINGS_GET = 0x0A
CMD_VIAL_QMK_SETTINGS_SET = 0x0B
CMD_VIAL_QMK_SETTINGS_RESET = 0x0C
CMD_VIAL_DYNAMIC_ENTRY_OP = 0x0D
DYNAMIC_VIAL_GET_NUMBER_OF_ENTRIES = 0x00
DYNAMIC_VIAL_TAP_DANCE_GET = 0x01
DYNAMIC_VIAL_TAP_DANCE_SET = 0x02
DYNAMIC_VIAL_COMBO_GET = 0x03
DYNAMIC_VIAL_COMBO_SET = 0x04
DYNAMIC_VIAL_KEY_OVERRIDE_GET = 0x05
DYNAMIC_VIAL_KEY_OVERRIDE_SET = 0x06
DYNAMIC_VIAL_ALT_REPEAT_KEY_GET = 0x07
DYNAMIC_VIAL_ALT_REPEAT_KEY_SET = 0x08

# ---- Vial Analog Protocol Extension (静电容/磁轴, 行程 0-255) ----
# 固件侧见 vial-qmk-wireless/docs/vial-analog-protocol.md
# v2：子命令从 0x0E-0x13 迁移到 0xF0-0xF5 高位段，
#     远离基础 Vial 子命令(0x00-0x0D 起)的上游低位增长区，规避冲突。
CMD_VIAL_ANALOG_GET_CAPS         = 0xF0
CMD_VIAL_ANALOG_GET_KEY_CONFIG   = 0xF1
CMD_VIAL_ANALOG_SET_KEY_CONFIG   = 0xF2
CMD_VIAL_ANALOG_GET_KEY_READINGS = 0xF3
CMD_VIAL_ANALOG_CALIBRATE        = 0xF4
CMD_VIAL_ANALOG_RESET_KEY        = 0xF5

ANALOG_AXIS_NONE = 0
ANALOG_AXIS_HALL = 1
ANALOG_AXIS_EC   = 2

ANALOG_CAP_PER_KEY_ACTUATION = (1 << 0)
ANALOG_CAP_RAPID_TRIGGER     = (1 << 1)
ANALOG_CAP_CALIBRATION       = (1 << 2)
ANALOG_CAP_LIVE_READINGS     = (1 << 3)
ANALOG_CAP_PER_KEY_RELEASE   = (1 << 4)
# bit5：固件支持 0xF4 mode4/5 触底校准开关（开启期间全部键等效 KC_NO）
ANALOG_CAP_BOTTOM_OUT_CAL    = (1 << 5)

ANALOG_FLAG_RT_ENABLED         = (1 << 0)
ANALOG_FLAG_ACTUATION_OVERRIDE = (1 << 1)
ANALOG_FLAG_CONTINUOUS         = (1 << 2)

ANALOG_CAL_SAMPLE_REST      = 0
ANALOG_CAL_SAMPLE_FULL      = 1
ANALOG_CAL_RESET            = 2
ANALOG_CAL_AUTO_PEAK        = 3
ANALOG_CAL_BOTTOM_OUT_ON    = 4  # 触底校准模式开：全部键等效 KC_NO，逐个按满即采集
ANALOG_CAL_BOTTOM_OUT_OFF   = 5  # 触底校准模式关

ANALOG_PROTOCOL_VERSION = 2  # 与固件 VIAL_ANALOG_PROTOCOL_VERSION 对应；v2=ID 迁移到 0xF0-0xF5

# how much of a macro/keymap buffer we can read/write per packet
BUFFER_FETCH_CHUNK = 28

# When did we get support for advanced macros (including delays in macros)
VIAL_PROTOCOL_ADVANCED_MACROS = 2
# Support for safe matrix tester (with unlock)
VIAL_PROTOCOL_MATRIX_TESTER = 3
# When did we get support for dynamic entries (tap dance, combos)
VIAL_PROTOCOL_DYNAMIC = 4
# When did we get support for qmk settings
VIAL_PROTOCOL_QMK_SETTINGS = 4
# When did we get support for 2-byte macros
VIAL_PROTOCOL_EXT_MACROS = 5
VIAL_PROTOCOL_KEY_OVERRIDE = 5
