# coding: utf-8

keymap = {
    "KC_MINUS": "{\n[",
    "KC_EQUAL": "}\n]",
    "KC_Q": "\"\n'",
    "KC_W": "<\n,",
    "KC_E": ">\n.",
    "KC_R": "P",
    "KC_T": "Y",
    "KC_Y": "F",
    "KC_U": "G",
    "KC_I": "C",
    "KC_O": "R",
    "KC_P": "L",
    "KC_LBRACKET": "?\n/",
    "KC_RBRACKET": "+\n=",
    "KC_A": "A",
    "KC_S": "O",
    "KC_D": "E",
    "KC_F": "U",
    "KC_G": "I",
    "KC_H": "D",
    "KC_J": "H",
    "KC_K": "T",
    "KC_L": "N",
    "KC_SCOLON": "S",
    "KC_QUOTE": "_\n-",
    "KC_Z": ":\n;",
    "KC_X": "Q",
    "KC_C": "J",
    "KC_V": "K",
    "KC_B": "X",
    "KC_N": "B",
    "KC_M": "M",
    "KC_COMMA": "W",
    "KC_DOT": "V",
    "KC_SLASH": "Z",
}
